*TODO*: Make Sarah a lawyer?

* Invasion Series

** Sentence Summary

Fairy beings invade earth, and humans fight back with help from other
creatures.

** Paragraph Summary

1. /[The Bitar sisters.]/ Colonies of blue angels to appear around the
   globe, and at first, countries try to approach them hopefully, but
   cautiously. However, at the first major conference between the angels
   and world leaders, the angels crystallize major cities around the
   globe.
2. /[Alex]/ The world tries to attack back, but they're quickly
   defeated, and the angels reveal that they want tribute, although
   exactly what the tribute will be is unclear.
3. /[Li Jiang.]/ Shapeshifters from the angels' world are also scattered
   around the earth, and they begin to help organize a rebellion.
   However, the shapeshifters are betrayed and all but one---who is
   severely injured and amnesiac---are killed.
4. /[Bethabara]/ People discover that the crystallized cities have
   actually been drawn into the fairy realm and that the passage between
   the two cities is actually porous. Angels train some of the humans as
   witches, and one has to draw her infant daughter back from Sha-Rin.
   In order to free herself, however, a magus gives his life, only to
   draw his mind into that of a new born infant's.
5. /[All]/ The infant and the daughter grow up to be ten or thirteen,
   and with the help of some of the fighters from previous books, they
   begin to penetrate Sha-Rin. This forces the angels to withdraw and
   close the gates, leaving the world a mess, but for humans again.

#+BEGIN_QUOTE
  The focus on all of these parts needs to be on people. Most of what I
  currently have above is just background to the real story. Re-write
  this paragraph summary focusing on the people. For each item, who are
  the major actors in that section? Who has the most to lose?
#+END_QUOTE

** Trilogy- and Book-Outline

*** Story Setup

/[The Bitar sisters.]/

**** I

#+BEGIN_QUOTE
  A woman tries to help her sister remember who she is while dodging the
  mob and the law.
#+END_QUOTE

Sarah, Sam's sister, stumbles into her sister's apartment with no memory
of who she was. The two sisters discover that the man whose wallet she
has was a government official who has evidently disappeared, just as
they're interrupted by the police, who are coming to interview his wife.
Sarah tries to re-establish ties with her life, as Sam knew it, but
angers her boss, a mobster, when she refuses to go back to work and
kills two of his henchmen, forcing the two to try to disappear. Sarah's
captured by the police when she tries to make contact with the widow
again, but she learns that he kept a dossier of state secrets, all of
them related to the paranormal, especially to the blue angels. The
sisters are able to frame the mobster for the man's death by planting
the folder in his location.

(He also had a small apartment where he let his preoccupation with the
angels get a little out of hand.)

**** II

#+BEGIN_QUOTE
  A woman and her sister travel into the desert outside Damascus to
  investigate a colony of blue angels.
#+END_QUOTE

Sarah and Sam have established an uneasy half-truce, which is
interrupted by Sam's handler at the agency, who wants her (them) to go
check out rumors of a colony of angels in the desert outside Damascus.
Sam angers their driver, and he dumps them at a set of ruins in the
desert. They are found by the angels, captured, and taken back to their
camp to be sent over. As they are led into a gateway, Sarah goes into
convulsions as her memories come back. The sisters escape from the
angels and Sha-Rin and are able to make contact with their handler.

**** III

#+BEGIN_QUOTE
  While the angels make themselves public, the woman's sister tries to
  come to terms with what she is, make contact with other shapeshifters,
  and stay with her "sister."
#+END_QUOTE

***** 0

***** 1

***** 2

***** 3

***** 4

*** Disasters

**** I

/[Alex is a handler in an agency similar to the one the Bitars work
with, but operated by South Africa. She's watching from a player, but
not a major one. And because Johannesburg isn't crystallized, South
Africa becomes a major player.]/

***** A

***** B

***** C

**** II

/[Li Jiang. (May need to work more on that name.)]/

***** A

***** B

***** C

**** III

/[Bethabara.]/

***** A

***** B

***** C

*** Story Conclusion

/[All.]/

**** I

**** II

**** III
