* Sentence Summary

Fairy beings invade earth, and humans fight back with help from other
creatures.

--------------

Take an hour and write a one-sentence summary of your novel. Something
like this: "A rogue physicist travels back in time to kill the apostle
Paul." (This is the summary for my first novel, Transgression.) The
sentence will serve you forever as a ten-second selling tool. This is
the big picture, the analog of that big starting triangle in the
snowflake picture.

When you later write your book proposal, this sentence should appear
very early in the proposal. It's the hook that will sell your book to
your editor, to your committee, to the sales force, to bookstore owners,
and ultimately to readers. So make the best one you can!

Some hints on what makes a good sentence:

-  Shorter is better. Try for fewer than 15 words.
-  No character names, please! Better to say "a handicapped trapeze
   artist" than "Jane Doe".
-  Tie together the big picture and the personal picture. Which
   character has the most to lose in this story? Now tell me what he or
   she wants to win.
-  Read the one-line blurbs on the New York Times Bestseller list to
   learn how to do this. Writing a one-sentence description is an art
   form.

* Paragraph Summary

#+BEGIN_QUOTE
  Fairy beings invade earth, and humans fight back with help from other
  creatures.
#+END_QUOTE

#+BEGIN_QUOTE
  How bad can it get? Heh-heh.
#+END_QUOTE

#+BEGIN_QUOTE
  I need to go through and make a lot of this real paragraphs about the
  story itself, not cryptic references to planning I've done earlier and
  elsewhere.
#+END_QUOTE

#+BEGIN_QUOTE
  What would a blog to create a community for these books look like?
#+END_QUOTE

#+BEGIN_QUOTE
  Move all of this stuff into one big outline.
#+END_QUOTE

* Paragraph Summary

** Story Setup

In bits and pieces, in remote and unexpected places, groups of blue
angels are appearing and establishing colonies. All the major
governments begin checking them out and establishing contact and
relations with them. They appear to be peaceful. But are they?

This will be the story of Sarah Bitar immediately after changing. The
trick will be setting up the rest of the story in subtle ways.

*** I

*** II

**** 0

**** 1

**** 2

**** 3

**** 4

*** III

**** 0

**** 1

**** 2

**** 3

**** 4

** Major Disasters

*** I

The angels meet with a collection of world leaders at the UN, and they
encase New York City and other major cities in a crystalline substance
that sings unsettlingly and dementedly. The angels then declare that the
earth is ruled by Sha-Rin, the leader of the angels. Or perhaps it's
their god. It's kind of hard to tell.

**** A

This is the story of the Bitars investigating the colony of angels in
the desert outside Damascus.

***** 1

***** 2

***** 3

**** B

A religion springs up around the angels while governments take a more
pragmatic approach.

***** 1

***** 2

***** 3

**** C

The angels agree to meet the world governments at the UN. But it's a
trap. New York City and other major world cities are crystallized.

***** 1

***** 2

***** 3

*** II

In response, armies attack, but it's chaotic. The angels are able to
easily parry the various armies against each other or defeat them
outright using what appears to be magic. But at the end of the battle,
there's little infrastructure left in major cities. In the meantime, the
angels start to insist upon tribute from the world governments---or more
likely from lower-level institutions and structures that are still
working. At first, everyone assumes that they want resources of some
kind, but at the end it becomes clear that they want people. (Children?
How dark is this going to be?)

**** A

***** 1

***** 2

***** 3

**** B

***** 1

***** 2

***** 3

**** C

***** 1

***** 2

***** 3

*** III

Shapeshifters, who've been lurking since long before the beginning, help
assemble a guerilla rebellion. It gains some small victories before
being crushed. In the process, most of the shapeshifters who remain are
killed. The one left has severe amnesia, which helped to keep her from
being killed. In the course of this set, it also becomes clear that the
realm of Sha-Rin is beginning to overlap the earth, that in a sense, the
earth is losing its identity and being drawn into the alternative
existence of Sha-Rin.

**** A

***** 1

***** 2

***** 3

**** B

***** 1

***** 2

***** 3

**** C

***** 1

***** 2

***** 3

*** IV

When New York was crystallized, from the inside it was actually pulled
into Sha-Rin. A small-time businessman was able to maintain his sanity
on the other side and begin to construct a world on the other side. On
this side his niece's infant is pulled into the other side (and people
realize that the permeability goes both ways, for what it's worth). The
niece is able to pull her daughter back, but at the expense of being
replaced in her life with a witch/changeling and being trapped inside a
prison. Eventually, she must work together with her husband to restore
her life after the witch takes off, and the businessman gives himself
(apparently), although in reality he's switched himself with an infant
being born on this side.

**** A

***** 1

***** 2

***** 3

**** B

***** 1

***** 2

***** 3

**** C

***** 1

***** 2

***** 3

*** V

This is going to be a little vague, especially since this is so late in
the series. I may flesh this out some as I outline the book level
preceding it.

-  Do I need another one between IV and V?
-  The businessman begins to grow up and is more than a little insane.
-  The girl grows up and has strange powers (and general strangeness
   herself).
-  More and more, people begin to penetrate Sha-Rin, wrecking havoc on
   that side as well.
-  This brings together the businessman, the girl, Elaine Li, and the
   Bitars.

**** A

***** 1

***** 2

***** 3

**** B

***** 1

***** 2

***** 3

**** C

***** 1

***** 2

***** 3

** Ending

Eventually, the angels must close the gates and withdraw in order to
protect Sha-Rin from the damage that's being caused by terrorists going
over there. Our world is still in a shambles, however. What will it take
to fix it?

** Explanation

 Take another hour and expand that sentence to a full paragraph
 describing the story setup, major disasters, and ending of the novel.
 This is the analog of the second stage of the snowflake. I like to
 structure a story as "three disasters plus an ending". Each of the
 disasters takes a quarter of the book to develop and the ending takes
 the final quarter. I don't know if this is the ideal structure, it's
 just my personal taste.

 If you believe in the Three-Act structure, then the first disaster
 corresponds to the end of Act 1. The second disaster is the mid-point of
 Act 2. The third disaster is the end of Act 2, and forces Act 3 which
 wraps things up. It is OK to have the first disaster be caused by
 external circumstances, but I think that the second and third disasters
 should be caused by the protagonist's attempts to "fix things." Things
 just get worse and worse.

 You can also use this paragraph in your proposal. Ideally, your
 paragraph will have about five sentences. One sentence to give me the
 backdrop and story setup. Then one sentence each for your three
 disasters. Then one more sentence to tell the ending. If this sounds
 suspiciously like back-cover copy, it's because . . . that's what it is
 and that's where it's going to appear someday.

* Character Page Summaries

The above gives you a high-level view of your novel. Now you need
something similar for the storylines of each of your characters.
Characters are the most important part of any novel, and the time you
invest in designing them up front will pay off ten-fold when you start
writing. For each of your major characters, take an hour and write a
one-page summary sheet that tells:

-  The character's name
-  A one-sentence summary of the character's storyline
-  The character's motivation (what does he/she want abstractly?)
-  The character's goal (what does he/she want concretely?)
-  The character's conflict (what prevents him/her from reaching this
   goal?)
-  The character's epiphany (what will he/she learn, how will he/she
   change?
-  A one-paragraph summary of the character's storyline

An important point: You may find that you need to go back and revise
your one-sentence summary and/or your one-paragraph summary. Go ahead!
This is good--it means your characters are teaching you things about
your story. It's always okay at any stage of the design process to go
back and revise earlier stages. In fact, it's not just okay--it's
inevitable. And it's good. Any revisions you make now are revisions you
won't need to make later on to a clunky 400 page manuscript.

Another important point: It doesn't have to be perfect. The purpose of
each step in the design process is to advance you to the next step. Keep
your forward momentum! You can always come back later and fix it when
you understand the story better. You will do this too, unless you're a
lot smarter than I am.

* Page Summary

Teresa is the queen of a city on the edge of a wasteland. There is a
faction of the court who doesn't like her, though, and wants to replace
her with a noblewoman. One of their complaints is that she hasn't
produced an heir yet. When she finally has a baby daughter, though, she
thinks that things are looking up. Then the child starts to act
strangely, to cry all the time, and to change physically too, subtly.
Teresa begins to suspect that her daughter has been replaced by a
changeling.

#+BEGIN_QUOTE
  This next part can spend some time getting ramped up and developing
  the important subplots of the coup attempt and the court drama against
  Teresa. Once that's underway, Teresa can attempt to draw Madeline
  back. After that, she goes to the witch-woman for advice when her
  mother doesn't have any.
#+END_QUOTE

Teresa is afraid to take action on the changeling immediately, but she
begins to probe and test to see where her daughter is and who is holding
her. She goes to consult the seer, who is no help whatsoever. While
she's trying to navigate some court intrigues, she holds off on doing
anything. Finally, she, her best friend, and her mother attempt to draw
her daughter, but they fail. And whoever is holding the child only
tightens her grip on them.

#+BEGIN_QUOTE
  I need some specific people for the court intrigue.
#+END_QUOTE

After her failure drawing the child, she finally goes to see the
witch-woman. She refuses to help Teresa, but she lets slip the location
of the mythical Gateway, and maybe something about the Mage (clues for
later). Meanwhile, Teresa's continued meetings, secretive and hurried,
raise Edward's suspicions. He enlists Oglevy to monitor her. Teresa
takes him into her confidence, and he twists this and mis-represents it
to Edward to make him more suspicious. Teresa takes a trip to visit her
birth mother at this point, and learns that everyone had thought that
her sister was a changeling before she disappeared down the river.
Edward becomes aware of Oglevy's troop movements, but he thinks that
Teresa and the priestesses are behind it, partially because of Teresa's
sudden absence. He has her arrested, and he starts bringing in the other
main priestesses too.

#+BEGIN_QUOTE
  Originally, she drew her guard in the next paragraph, but I want her
  to escape without magic.
#+END_QUOTE

After some inexplicable interrogations, and just before her execution,
Teresa is able to escape. She crosses the river into the Desolate
Kingdom, and with great adventure and sacrifice, she makes it across to
the Gateway. Teresa is alone at this point, and she crosses over. The
Mage meets her and takes her to her sister, who is addled, and who has
Madeline. But Teresa cannot take the child from her, and she cannot have
it cross back anyway. [Why? That seems odd.] She also learns who her
sister's changeling became, and what her purpose was. In the end, the
Mage has to pull her away, both for her own sanity, and because Edward
has caught up with her and is preparing to attack the Gateway.

Back in her world, Teresa stops Edward from attacking the Gateway. They
return home, to find Oglevy already in the palace. They are able to
escape, and Teresa helps Edward take the castle back. Once that's
settled, she visits the witch-woman again, and offers her her own place.
The witch-woman was supposed to be /her/ changeling, and Teresa offers
to let her become that---in exchange for getting her child back. The
witch-woman agrees and draws then child. She then leaves, after binding
Teresa and the child to the cave.

--------------

By this stage, you should have a good idea of the large-scale structure
of your novel, and you have only spent a day or two. Well, truthfully,
you may have spent as much as a week, but it doesn't matter. If the
story is broken, you know it now, rather than after investing 500 hours
in a rambling first draft. So now just keep growing the story. Take
several hours and expand each sentence of your summary paragraph into a
full paragraph. All but the last paragraph should end in a disaster. The
final paragraph should tell how the book ends.

This is a lot of fun, and at the end of the exercise, you have a pretty
decent one-page skeleton of your novel. It's okay if you can't get it
all onto one single-spaced page. What matters is that you are growing
the ideas that will go into your story. You are expanding the conflict.
You should now have a synopsis suitable for a proposal, although there
is a better alternative for proposals . . .

* Character synopses

Take a day or two and write up a one-page description of each major
character and a half-page description of the other important characters.
These "character synopses" should tell the story from the point of view
of each character. As always, feel free to cycle back to the earlier
steps and make revisions as you learn cool stuff about your characters.
I usually enjoy this step the most and lately, I have been putting the
resulting "character synopses" into my proposals instead of a plot-based
synopsis. Editors love character synopses, because editors love
character-based fiction.

* Plot synopsis

By now, you have a solid story and several story-threads, one for each
character. Now take a week and expand the one-page plot synopsis of the
novel to a four-page synopsis. Basically, you will again be expanding
each paragraph from step (4) into a full page. This is a lot of fun,
because you are figuring out the high-level logic of the story and
making strategic decisions. Here, you will definitely want to cycle back
and fix things in the earlier steps as you gain insight into the story
and new ideas whack you in the face.

* Character worksheets

Take another week and expand your character descriptions into
full-fledged character charts detailing everything there is to know
about each character. The standard stuff such as birthdate, description,
history, motivation, goal, etc. Most importantly, how will this
character change by the end of the novel? This is an expansion of your
work in step (3), and it will teach you a lot about your characters. You
will probably go back and revise steps (1-6) as your characters become
"real" to you and begin making petulant demands on the story. This is
good -- great fiction is character-driven. Take as much time as you need
to do this, because you're just saving time downstream. When you have
finished this process, (and it may take a full month of solid effort to
get here), you are ready to write a proposal and sell this novel. Do so.

* Plot outline

You may or may not take a hiatus here, waiting for the book to sell. At
some point, you've got to actually write the novel. Before you do that,
there are a couple of things you can do to make that traumatic first
draft easier. The first thing to do is to take that four-page synopsis
and make a list of all the scenes that you'll need to turn the story
into a novel. And the easiest way to make that list is . . . with a
spreadsheet.

For some reason, this is scary to a lot of writers. Oh the horror. Deal
with it. You learned to use a word-processor. Spreadsheets are easier.
You need to make a list of scenes, and spreadsheets were invented for
making lists. If you need some tutoring, buy a book. There are a
thousand out there, and one of them will work for you. It should take
you less than a day to learn the itty bit you need. It'll be the most
valuable day you ever spent. Do it.

Make a spreadsheet detailing the scenes that emerge from your four-page
plot outline. Make just one line for each scene. In one column, list the
POV character. In another (wide) column, tell what happens. If you want
to get fancy, add more columns that tell you how many pages you expect
to write for the scene. A spreadsheet is ideal, because you can see the
whole storyline at a glance, and it's easy to move scenes around to
reorder things.

My spreadsheets usually wind up being over 100 lines long, one line for
each scene of the novel. As I develop the story, I make new versions of
my story spreadsheet. This is incredibly valuable for analyzing a story.
It can take a week to make a good spreadsheet. When you are done, you
can add a new column for chapter numbers and assign a chapter to each
scene.

What should you note for each scene?

-  POV character
-  that character's goal
-  conflicts/obstructions to the goal
-  resolution of the conflict with a twist or surprise that moves the
   story forward
-  the scene's subtext, the character's inner conflict

And for sequels:

-  an emotion
-  a quandary over what to do
-  a decision
-  an action based on the decision

* Narrative outline

(Optional. I don't do this step anymore.) Switch back to your word
processor and begin writing a narrative description of the story. Take
each line of the spreadsheet and expand it to a multi-paragraph
description of the scene. Put in any cool lines of dialogue you think
of, and sketch out the essential conflict of that scene. If there's no
conflict, you'll know it here and you should either add conflict or
scrub the scene.

I used to write either one or two pages per chapter, and I started each
chapter on a new page. Then I just printed it all out and put it in a
loose-leaf notebook, so I could easily swap chapters around later or
revise chapters without messing up the others. This process usually took
me a week and the end result was a massive 50-page printed document that
I would revise in red ink as I wrote the first draft. All my good ideas
when I wake up in the morning got hand-written in the margins of this
document. This, by the way, is a rather painless way of writing that
dreaded detailed synopsis that all writers seem to hate. But it's
actually fun to develop, if you have done steps (1) through (8) first.
When I did this step, I never showed this synopsis to anyone, least of
all to an editor -- it was for me alone. I liked to think of it as the
prototype first draft. Imagine writing a first draft in a week! Yes, you
can do it and it's well worth the time. But I'll be honest, I don't feel
like I need this step anymore, so I don't do it now.

* First draft

At this point, just sit down and start pounding out the real first draft
of the novel. You will be astounded at how fast the story flies out of
your fingers at this stage. I have seen writers triple their writing
speed overnight, while producing better quality first drafts than they
usually produce on a third draft.

You might think that all the creativity is chewed out of the story by
this time. Well, no, not unless you overdid your analysis when you wrote
your Snowflake. This is supposed to be the fun part, because there are
many small-scale logic problems to work out here. How does Hero get out
of that tree surrounded by alligators and rescue Heroine who's in the
burning rowboat? This is the time to figure it out! But it's fun because
you already know that the large-scale structure of the novel works. So
you only have to solve a limited set of problems, and so you can write
relatively fast.

This stage is incredibly fun and exciting. I have heard many writers
complain about how hard the first draft is. Invariably, they are
seat-of-the-pants writers who have no clue what's coming next. Good
grief! Life is too short to write like that! There is no reason to spend
500 hours writing a wandering first draft of your novel when you can
write a solid one in 150. Counting the 100 hours it takes to do the
design documents, you come out way ahead in time.

(I'll note that many seat-of-the-pants writers shriek at the thought of
doing a Snowflake document. That's fine. Different people are different.
I suspect you know already whether the Snowflake is something that's
going to work for you or not. Even if it does work for you, I'd
encourage you to improvise on it. May a thousand different Snowflake
methods bloom!) There is not just one solution to the problem of how to
write a novel, there are many. Use the one that works for you.

About midway through a first draft, I usually take a breather and fix
all the broken parts of my design documents. Yes, the design documents
are not perfect! That's okay! The design documents are not fixed in
concrete, they are a living set of documents that grows as you develop
your novel. If you are doing your job right, at the end of the first
draft you will laugh at what an amateurish piece of junk your design
documents were. And you'll be thrilled at how deep your story has
become.

That's All! That's the Snowflake Method. It works for me and for many of
my writer friends who have tried it. I've lost track of how many people
around the world who have emailed me to say that the Snowflake helped
them get their novel on track. So it works for a lot of people. I hope
it works for you.
